run:
  timeout: 10m
linters:
  enable:
    - asciicheck
    - bidichk
    # - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - gochecknoinits
    - goconst
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - wsl

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goheader:
    values:
      regexp:
        date: "20[1-2][0-9]"
    template: |-
      Copyright {{date}} The Swarm Authors. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
issues:
  exclude-rules:
    - linters:
        - forbidigo
      path: cmd/
      text: "use of `fmt.Print" ## allow fmt.Print in cmd directory
