name: run-on-issue

on:
  issues:
    types: [opened, edited]

jobs:
 run-on-issue:
     strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-latest
    if:  startsWith(github.event.issue.title, 'run node-funder')
    setps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: run node-funder
        run: go run ./cmd -chainNodeEndpoint=${{secrets.CHAIN_NODE_ENDPOINT}} -walletKey=${{secrets.WALLET_KEY}} ${{github.event.issue.body}}
