name: run-on-issue

on:
  issues:
    types: [opened, edited]

jobs:
  run-on-issue:
  #  if:  startsWith(github.event.issue.title, 'run node-funder')
    runs-on: ubuntu-latest
    setps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: run node-funder
        run: go run ./cmd -chainNodeEndpoint="${{secrets.CHAIN_NODE_ENDPOINT}}" -walletKey="${{secrets.WALLET_KEY}}" ${{github.event.issue.body}}
